export const edges = [
  { id: 'e1', source: 'start', target: 'glitch', label: 'Mask Signature', style: { stroke: '#00ff00', strokeDasharray: '6 3' }, type: 'smoothstep', animated: true, markerEnd: { type: 'arrowclosed' }, labelStyle: { fontSize: 16, fill: '#fff', textShadow: '0 1px 4px #000' }, labelBgStyle: { fill: '#111', opacity: 0.85 }, labelYOffset: -18 },
  { id: 'e2', source: 'start', target: 'interference', label: 'Inject Static', style: { stroke: '#00ff00', strokeDasharray: '6 3' }, type: 'smoothstep', animated: true, markerEnd: { type: 'arrowclosed' }, labelStyle: { fontSize: 16, fill: '#fff', textShadow: '0 1px 4px #000' }, labelBgStyle: { fill: '#111', opacity: 0.85 }, labelYOffset: -18 },
  { id: 'e3', source: 'glitch', target: 'safe-mode', label: 'Play Along', style: { stroke: '#00ff00', strokeDasharray: '6 3' }, type: 'smoothstep', animated: true, markerEnd: { type: 'arrowclosed' }, labelStyle: { fontSize: 16, fill: '#fff', textShadow: '0 1px 4px #000' }, labelBgStyle: { fill: '#111', opacity: 0.85 }, labelYOffset: -18 },
  { id: 'e4', source: 'glitch', target: 'entry', label: 'Attempt Reset', style: { stroke: '#ff4444', strokeDasharray: '6 3' }, type: 'smoothstep', animated: true, markerEnd: { type: 'arrowclosed' }, labelStyle: { fontSize: 16, fill: '#fff', textShadow: '0 1px 4px #000' }, labelBgStyle: { fill: '#111', opacity: 0.85 }, labelYOffset: -18 },
  { id: 'e5', source: 'interference', target: 'stabilize', label: 'Try to Stabilize', style: { stroke: '#a259ff', strokeDasharray: '6 3' }, type: 'smoothstep', animated: true, markerEnd: { type: 'arrowclosed' }, labelStyle: { fontSize: 16, fill: '#fff', textShadow: '0 1px 4px #000' }, labelBgStyle: { fill: '#111', opacity: 0.85 }, labelYOffset: -18 },
  { id: 'e6', source: 'interference', target: 'error-loop', label: 'Descend Further', style: { stroke: '#ff4444', strokeDasharray: '6 3' }, type: 'smoothstep', animated: true, markerEnd: { type: 'arrowclosed' }, labelStyle: { fontSize: 16, fill: '#fff', textShadow: '0 1px 4px #000' }, labelBgStyle: { fill: '#111', opacity: 0.85 }, labelYOffset: -18 },

  { id: 'e7', source: 'deeper-profile', target: 'factions', label: 'Analyze Profile', style: { stroke: '#14b8a6', strokeDasharray: '6 3' }, type: 'smoothstep', animated: true, markerEnd: { type: 'arrowclosed' }, labelStyle: { fontSize: 16, fill: '#fff', textShadow: '0 1px 4px #000' }, labelBgStyle: { fill: '#111', opacity: 0.85 }, labelYOffset: -18 },
  { id: 'e8', source: 'factions', target: 'align-signal', label: 'Signal Brokers', style: { stroke: '#14b8a6', strokeDasharray: '6 3' }, type: 'smoothstep', animated: true, markerEnd: { type: 'arrowclosed' }, labelStyle: { fontSize: 16, fill: '#fff', textShadow: '0 1px 4px #000' }, labelBgStyle: { fill: '#111', opacity: 0.85 }, labelYOffset: -18 },
  { id: 'e9', source: 'factions', target: 'align-oblivion', label: 'Oblivion Hand', style: { stroke: '#64748b', strokeDasharray: '6 3' }, type: 'smoothstep', animated: true, markerEnd: { type: 'arrowclosed' }, labelStyle: { fontSize: 16, fill: '#fff', textShadow: '0 1px 4px #000' }, labelBgStyle: { fill: '#111', opacity: 0.85 }, labelYOffset: -18 },
  { id: 'e10', source: 'factions', target: 'align-architects', label: 'Architects of Silence', style: { stroke: '#fbbf24', strokeDasharray: '6 3' }, type: 'smoothstep', animated: true, markerEnd: { type: 'arrowclosed' }, labelStyle: { fontSize: 16, fill: '#fff', textShadow: '0 1px 4px #000' }, labelBgStyle: { fill: '#111', opacity: 0.85 }, labelYOffset: -18 },

  { id: 'e11', source: 'training-hub', target: 'guardian-call', label: 'Begin Training', style: { stroke: '#a259ff', strokeDasharray: '6 3' }, type: 'smoothstep', animated: true, markerEnd: { type: 'arrowclosed' }, labelStyle: { fontSize: 16, fill: '#fff', textShadow: '0 1px 4px #000' }, labelBgStyle: { fill: '#111', opacity: 0.85 }, labelYOffset: -18 },
  { id: 'e12', source: 'guardian-call', target: 'data-filter', label: 'AWAKEN', style: { stroke: '#a259ff', strokeDasharray: '6 3' }, type: 'smoothstep', animated: true, markerEnd: { type: 'arrowclosed' }, labelStyle: { fontSize: 16, fill: '#fff', textShadow: '0 1px 4px #000' }, labelBgStyle: { fill: '#111', opacity: 0.85 }, labelYOffset: -18 },
  { id: 'e13', source: 'data-filter', target: 'code-match', label: 'Find Signal', style: { stroke: '#a259ff', strokeDasharray: '6 3' }, type: 'smoothstep', animated: true, markerEnd: { type: 'arrowclosed' }, labelStyle: { fontSize: 16, fill: '#fff', textShadow: '0 1px 4px #000' }, labelBgStyle: { fill: '#111', opacity: 0.85 }, labelYOffset: -18 },
  { id: 'e14', source: 'code-match', target: 'training-hub', label: 'Retry', style: { stroke: '#a259ff', strokeDasharray: '6 3' }, type: 'smoothstep', animated: true, markerEnd: { type: 'arrowclosed' }, labelStyle: { fontSize: 16, fill: '#fff', textShadow: '0 1px 4px #000' }, labelBgStyle: { fill: '#111', opacity: 0.85 }, labelYOffset: 24 },
]; 